# kubectl config set-credentials martin --client-certificate=/root/martin.crt --client-key=/root/martin.key
# kubectl config set-context developer --user=martin --cluster=kubernetes
# kubectl config set-context --current --namespace=development
# k run jekyll --image=kodekloud/jekyll-serve --labels="run=jekyll"
# k get po jekyll -o yaml > pod.yaml
# k create -f pod.yaml
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: jekyll
  name: jekyll
  namespace: development
spec:
  containers:
  - image: kodekloud/jekyll-serve
    name: jekyll
    volumeMounts:
    - mountPath: /site
      name: site
  initContainers:
  - name: copy-jekyll-site
    image: kodekloud/jekyll
    command: ['jekyll', 'new', 'site']
    volumeMounts:
    - mountPath: /site
      name: site
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: jekyll-site
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
  namespace: development
spec: 
 accessModes:
    - ReadWriteMany
 volumeMode: Filesystem
 resources:
   requests:
     storage: 1Gi
 storageClassName: local-storage

