# kubectl get nodes
# vi /root/.kube/config
# Correct the port number
# crictl ps -a | grep -i api
# docker ps -a | grep -i api
# docker logs containerID
# kubectl uncordon node01
# scp -r /media/* node01:/test
# k get -n kube-system po
# k get deploy -n kube-system
# k edit deployment -n kube-system coredns

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec: 
 capacity:
   storage: 1Gi
 accessModes:
    - ReadWriteMany
 volumeMode: Filesystem
 persistentVolumeReclaimPolicy: Recycle
 storageClassName: local-storage
 hostPath:
   path: /web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec: 
 accessModes:
    - ReadWriteMany
 volumeMode: Filesystem
 resources:
   requests:
     storage: 1Gi
 storageClassName: local-storage
